costs/urls.py
from django.urls import path

from . import views

app_name = 'costs'

urlpatterns = [
    path('', views.index, name='index'),
    path('applikasjon_form', views.application_form, name='application_form'),

    path('applikasjon', views.application, name='application'),
    path('applikasjon/<str:name>', views.application, name='application'),
    path('fordeling', views.cost_distribution, name='cost_distribution'),
    path('fordeling_slett', views.cost_distribution_delete, name='cost_distribution_delete'),
    path('server/form', views.server_form, name='server_form'),
    path('server/<str:customer>/<str:name>', views.server_detail, name='server'),
    path('servere', views.servers_all, name='servers'),
    path('servere/<str:customer>', views.servers_all, name='servers'),
    path('arbeidsstasjoner', views.workstations, name='workstations'),
    path('arbeidsstasjon', views.workstation, name='workstation'),
    path('kunder', views.customers, name='customers'),
    path('portefolje', views.portfolio, name='portfolio'),
    path('applikasjoner', views.applications, name='applications'),
    path('applikasjoner/kunde/<str:customer>', views.applications, name='applications'),
    path('applikasjoner/kunde/<str:customer>/<str:department>', views.applications, name='applications'),
    path('applikasjoner/kunde/<str:customer>/sektor/<int:sector>', views.applications, name='applications'),
    path('applikasjoner/leverandor/<str:vendor>', views.applications, name='applications'),
    path('sectors', views.sectors, name='sectors'),
    path('ansvar', views.departments, name='departments'),
    path('accounts/profile/', views.applications),
    path('rapport', views.report, name='report'),
    path('lisenser', views.licenses, name='licences'),
    path('import/sccm', views.import_sccm),
    path('tjenesteleveranse', views.product_delivery, name='product_delivery'),
    path('kunde/firma', views.customer_company, name='customer_company'),
    path('tjenester', views.products, name='products'),
    path('tjenestebrukere', views.product_users, name='product_users'),
    path('bruker', views.user, name='user'),
    path('brukere', views.users, name='users'),
]

storfollo_costs/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('costs.urls')),
    path('employee/', include('employee_info.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

costs/models.py
import datetime

from django.db import models
from django.db.models import Sum
from employee_info.models import Function, Resource, CostCenter, Company

from ad_import.models import Directory
from ad_import.models import Server as ADServer
from ad_import.models import User as ADUser
from ad_import.models import Workstation as ADWorkstation


class Customer(models.Model):
    id = models.CharField(primary_key=True, max_length=5)
    name = models.CharField('Navn', max_length=50)
    served_by = models.ForeignKey('self', blank=True, null=True, on_delete=models.PROTECT, verbose_name='Driftes av')
    ad_directories = models.ManyToManyField(Directory)

    class Meta:
        verbose_name = 'kunde'
        verbose_name_plural = 'kunder'

    def __str__(self):
        return self.name

    def costs(self):
        cost = 0
        for application in self.applications.all():
            cost += application.cost()
        for product in self.deliveries.all():
            cost += product.sum()

        return cost

    def servers_active(self, days=90):
        return self.servers.filter(last_logon__gte=datetime.datetime.today() - datetime.timedelta(days=days))

    def workstations_active(self, days=90):
        return self.workstations.filter(last_logon__gte=datetime.datetime.today() - datetime.timedelta(days=days))

    def users(self):
        return User.objects.filter(department__customer=self)


class ProductType(models.Model):
    type = models.CharField('Tjenestetype', max_length=50)
    description = models.TextField('Beskrivelse', null=True, blank=True)

    class Meta:
        verbose_name = 'tjenestetype'
        verbose_name_plural = 'tjenestetyper'

    def __str__(self):
        return self.type


class Product(models.Model):
    name = models.CharField('Tjeneste', max_length=50)
    type = models.ForeignKey(ProductType, on_delete=models.PROTECT, verbose_name='Tjenestetype')
    price = models.IntegerField('Pris per måned')

    class Meta:
        verbose_name = 'tjeneste'
        verbose_name_plural = 'tjenester'

    def __str__(self):
        return '%s: %s' % (self.type, self.name)


class Server(models.Model):
    name = models.CharField('Navn', max_length=50)
    dns_name = models.CharField('DNS-navn', max_length=100, null=True, blank=True)
    dn = models.CharField('DN', max_length=200, null=True, blank=True)
    ip = models.GenericIPAddressField(null=True, blank=True, default=None)
    description = models.CharField('Beskrivelse', max_length=100, null=True, blank=True)
    last_logon = models.DateTimeField('Sist aktiv', null=True, blank=True)
    last_update = models.DateTimeField('Sist oppdatert', auto_now=True)
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='servers', verbose_name='Tjeneste',
                                null=True)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT, verbose_name='Kunde', related_name='servers')
    imported = models.BooleanField(default=False)
    ad_object = models.OneToOneField(ADServer, on_delete=models.CASCADE, null=True, blank=True, default=None, verbose_name='AD')

    class Meta:
        unique_together = ['name', 'customer']
        verbose_name = 'server'
        verbose_name_plural = 'servere'
        ordering = ['customer', 'name']

    def __str__(self):
        value = '%s: %s' % (self.customer, self.name)
        if self.product:
            value += ' (%s)' % self.product
        return value

    def applications_string(self):
        apps_string = ''
        for app in self.applications.all():
            apps_string += str(app) + "\n"

        return apps_string

    def application_cost(self):
        """
        Application cost per month
        :return:
        """

        if not self.product or not self.product.price or self.applications.count() == 0:
            return 0
        return round(self.product.price / self.applications.count())


class Department(models.Model):
    number = models.IntegerField('Ansvar')
    name = models.CharField('Navn', max_length=100)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT, related_name='departments')

    class Meta:
        unique_together = ['number', 'customer']
        verbose_name = 'ansvar'
        verbose_name_plural = 'ansvar'
        ordering = ['name']

    def __str__(self):
        return '%s (%s)' % (self.name, self.customer)

    def sector(self):
        try:
            return self.sector_dep.get(departments__number=self.number)
        except Sector.MultipleObjectsReturned as e:
            print(e)
            print('Department %s matched multiple sectors:' % self)
            sectors = self.sector_dep.filter(departments__number=self.number)
            for sector in sectors:
                print(sector)
            return sectors.first()


class User(models.Model):
    number = models.IntegerField('Ressursnummer', null=True)
    ad_user = models.CharField('Brukernavn AD', max_length=50)
    ad_object = models.OneToOneField(ADUser, on_delete=models.CASCADE, null=True, default=None, verbose_name='AD',
                                     related_name='users')
    name = models.CharField('Navn', max_length=100, null=True)
    employee = models.ForeignKey(Resource, on_delete=models.CASCADE, verbose_name='ansatt', null=True, default=None)
    email = models.EmailField('Epostadresse', null=True)
    dn = models.CharField('DN', max_length=300, blank=True, null=True)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT, verbose_name='Kunde', null=True, default=None)

    class Meta:
        verbose_name = 'bruker'
        verbose_name_plural = 'brukere'
        ordering = ['name']

    def company(self):
        if self.employee:
            return self.employee.company

    def department(self) -> CostCenter:
        if self.employee:
            main_position = self.employee.main_position()
            if main_position:
                return main_position.costCenter

    def last_logon(self):
        if self.ad_object:
            return self.ad_object.lastLogon

    def last_update(self):
        if self.ad_object:
            return self.ad_object.last_update

    def has_ad(self):
        return self.ad_object is not None

    def display_name(self):
        return self.ad_object.displayName

    def username(self):
        return self.ad_object.sAMAccountName

    def __str__(self):
        return '%s (%s)' % (self.name, self.customer)


class Application(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT, verbose_name='Kunde', related_name='applications')
    name = models.CharField('Applikasjonsnavn', max_length=100)
    vendor = models.CharField('Leverandør', max_length=100)
    cloud = models.BooleanField('Skytjeneste')
    servers = models.ManyToManyField(Server, verbose_name='Servere', related_name='applications', blank=True)
    department = models.ForeignKey(Department, on_delete=models.PROTECT, blank=True, null=True, verbose_name='Ansvar')
    integrations = models.ManyToManyField('self', verbose_name='Integrasjoner', related_name='integrated', blank=True)
    licence_cost = models.IntegerField('Lisenskostnad', default=0)
    internal_hours = models.IntegerField('Applikasjonsdrift timer pr mnd', default=0)
    external_cost = models.IntegerField('Konsulentkostnad', default=0)
    responsible = models.ForeignKey(User, verbose_name='Systemansvarlig', on_delete=models.PROTECT,
                                    related_name='responsible', blank=True, null=True)
    super_user = models.ForeignKey(User, verbose_name='Superbruker', on_delete=models.PROTECT,
                                   related_name='super_user', blank=True, null=True)

    def __str__(self):
        return '%s: %s' % (self.customer, self.name)

    class Meta:
        verbose_name = 'applikasjon'
        verbose_name_plural = 'applikasjoner'
        unique_together = ['customer', 'name', 'department']
        ordering = ['customer', 'name']

    def internal_hour_cost(self):
        product = Product.objects.get(name='Drift av applikasjon per time')
        return self.internal_hours * product.price

    def internal_hour_cost_year(self):
        return self.internal_hour_cost() * 12

    def server_cost(self):
        """
        Server cost per month
        :return:
        """
        server_cost = 0
        for server in self.servers.all():
            server_cost += server.application_cost()
        return server_cost

    def server_cost_year(self):
        return self.server_cost() * 12

    def external_cost_total(self):
        return self.external_cost + self.licence_cost

    def cost(self):
        return self.server_cost() + self.external_cost + self.licence_cost

    def internal_cost_total_year(self):
        return self.internal_hour_cost_year() + self.server_cost_year()

    def total_year(self):
        return self.server_cost_year() + self.external_cost_total() + self.internal_hour_cost_year()


class CostDistribution(models.Model):
    application = models.ForeignKey(Application, on_delete=models.CASCADE, verbose_name='applikasjon',
                                    related_name='distributions')
    company = models.ForeignKey(Company, on_delete=models.CASCADE, verbose_name='firma')
    percentage = models.IntegerField(verbose_name='prosent')

    account = models.CharField('konto', max_length=6)
    cost_center = models.ForeignKey(CostCenter, on_delete=models.PROTECT, blank=True, null=True,
                                    verbose_name='ansvar')
    function = models.ForeignKey(Function, on_delete=models.PROTECT, verbose_name='funksjon')

    class Meta:
        unique_together = ['application', 'company', 'account', 'cost_center', 'function']

    def is_valid(self):
        lines = self.objects.filter(application=self.application)
        percent_sum = lines.aggregate(Sum('percentage'))['percentage__sum']
        return percent_sum == 100

costs/models/CostDistribution.py
from django.db import models
from employee_info.models import CostCenter, Function

from . import Application


class CostDistribution(models.Model):
    application = models.ForeignKey(Application, on_delete=models.CASCADE, verbose_name='applikasjon',
                                    related_name='distributions')
    percentage = models.IntegerField(verbose_name='prosent')

    account = models.CharField('konto', max_length=6)
    cost_center = models.ForeignKey(CostCenter, on_delete=models.PROTECT, blank=True, null=True,
                                    verbose_name='ansvar')
    function = models.ForeignKey(Function, on_delete=models.PROTECT, verbose_name='funksjon')

    class Meta:
        unique_together = ['application', 'account', 'cost_center', 'function']
        verbose_name = 'kostnadsfordeling'
        verbose_name_plural = 'kostnadsfordelinger'

    def __str__(self):
        return '%s%% of %skr = %skr' % (
            self.percentage, self.application.total_year(), self.amount())

    def customer(self):
        return self.application.customer

    def amount(self):
        return self.application.total_year() * (self.percentage/100)

costs/models/Department.py
from django.db import models

from costs.models import Customer


class Department(models.Model):
    number = models.IntegerField('Ansvar')
    name = models.CharField('Navn', max_length=100)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT, related_name='departments')

    class Meta:
        unique_together = ['number', 'customer']
        verbose_name = 'ansvar'
        verbose_name_plural = 'ansvar'
        ordering = ['name']

    def __str__(self):
        return '%s (%s)' % (self.name, self.customer)

costs/models/Sector.py
from django.db import models

from . import Customer, Department


class Sector(models.Model):
    name = models.CharField('Navn', max_length=50)
    departments = models.ManyToManyField(Department, verbose_name='Ansvar', blank=True, related_name='sector_dep')
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name='Kunde', related_name='sectors')

    def servers(self):
        from . import Server
        return Server.objects.filter(
            applications__in=self.applications.all()
        )

    def costs(self):
        """
        Costs per year
        """
        cost = 0
        for app in self.applications.all():
            cost += app.total_year()
        for delivery in self.deliveries.all():
            cost += delivery.sum_year()

        return cost

    def external_costs(self):
        """
        External cost per year
        """
        cost = 0
        for app in self.applications.all():
            cost += app.external_cost

        return cost

    def licence_costs(self):
        """
        Licence cost per year
        """
        cost = 0
        for app in self.applications.all():
            cost += app.licence_cost

        return cost

    def server_costs(self):
        """
        Server cost per year
        """
        cost = 0
        for app in self.applications.all():
            cost += app.server_cost_year()

        return cost

    def __str__(self):
        return '%s %s' % (self.customer, self.name)

    class Meta:
        verbose_name = 'Sektor'
        verbose_name_plural = 'Sektorer'
        unique_together = ['name', 'customer']
        ordering = ['name']

costs/models/Student.py
from django.db import models

from costs.models import Customer


class Student(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    firstName = models.CharField('fornavn', max_length=200)
    lastName = models.CharField('etternavn', max_length=200)
    ssn = models.CharField('fødselsnummer', max_length=11)
    guid = models.CharField('GUID', max_length=36)

    def __str__(self):
        return self.firstName + ' ' + self.lastName

costs/forms.py
from django import forms

from costs.models import Application, CostDistribution, Server, ProductDelivery


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        # TODO: Rewrite user selection with AJAX autocomplete
        # <select> elements makes the load too slow
        exclude = ['responsible', 'super_user']


class ServerForm(forms.ModelForm):
    class Meta:
        model = Server
        exclude = ['ad_object', 'imported', 'last_update', 'last_logon']


class CostDistributionForm(forms.ModelForm):
    class Meta:
        model = CostDistribution
        exclude = ['application', 'company']


class ProductDeliveryForm(forms.ModelForm):
    class Meta:
        model = ProductDelivery
        exclude = ['sector'] # , 'cost_center', 'function'
        widgets = {
            'cost_center': forms.TextInput(),
            'function': forms.TextInput(),
        }

costs/templates/costs/application.html
{% extends 'costs/base.html' %}
{% load humanize %}
{% block body %}
    {% for application in applications %}
        <h2>{{ application.customer }}</h2>
        <h3>Informasjon</h3>
        <table>
        {% if application.sector %}
            <tr>
                <th>{{ fields.sector }}</th>
                <td>{{ application.sector.name }}</td>
            </tr>
        {% endif %}
        {% if application.vendor %}
            <tr>
                <th>{{ fields.vendor }}</th>
                <td>{{ application.vendor }}</td>
            </tr>
        {% endif %}
        {% if application.responsible %}
            <tr>
                <th>{{ fields.responsible }}</th>
                <td>{{ application.responsible }}</td>
            </tr>
        {% endif %}
        {% if application.super_user %}
            <tr>
                <th>{{ fields.super_user }}</th>
                <td>{{ application.super_user }}</td>
            </tr>
        {% endif %}
        </table>
        {% if application.servers.count %}
        <h3>Servere</h3>
        <table>
        <tr>
            {% if perms.costs.view_server %}
            <th>Navn</th>
            {% endif %}
            <th>Type</th>
            <th>Tjeneste</th>
        <th title="Applikasjonens andel av serverens driftskostnad per m&aring;ned">Kostnad</th>
        </tr>
            {% for server in application.servers.all %}
                <tr>
                {% if perms.costs.view_server %}
                    <th><a href="{% url 'costs:server' customer=server.customer name=server.name %}">{{ server.name }}</a></th>
                {% endif %}
                <td>{{ server.type|default:"" }}</td>
                    <td>{{ server.product.name }}</td>
                <td>{{ server.application_cost|intcomma }}kr</td>
                </tr>
            {% endfor %}
        {% endif %}
        </table>
        {% if application.integrations.count %}
        <h3>Integrert med</h3>
        <table>
        <tr>
            <th>Applikasjon</th>
            <th>Sektor</th>
        </tr>
        {% for integration in application.integrations.all %}
        <tr>
            <th><a href="{% url 'costs:application' %}?name={{ integration.name|urlencode }}&amp;customer={{ integration.customer.id|urlencode }}">{{ integration.name }}</a></th>
            <td>{{ integration.department.sector.name }}</td>
        </tr>
        {% endfor %}
        </table>
        {% endif %}

        <h3>&Aring;rlige kostnader</h3>
        <table>
            <tr>
                <th>Lisens</th>
                <td data-sort="{{ application.licence_cost }}">{{ application.licence_cost|intcomma }}kr</td>
            </tr>
            {% if application.external_cost %}
            <tr>
                <th>Konsulent</th>
                <td data-sort="{{ application.external_cost }}">{{ application.external_cost|intcomma }}kr</td>
            </tr>
            {% endif %}
            {% if application.internal_hours %}
            <tr>
                <th>StorFollo IKT drift</th>
                <td data-sort="{{ application.internal_hour_cost_year }}">{{ application.internal_hour_cost_year|intcomma }}kr</td>
            </tr>
            {% endif %}
            {% if application.servers.count %}
            <tr>
                <th>{{ application.servers.count }} server(e):</th>
                <td data-sort="{{ application.server_cost_year }}">{{ application.server_cost_year|intcomma }}kr</td>
            </tr>
            {% endif %}
            <tr>
                <th>Totalt</th>
                <td>{{ application.total_year|intcomma }}kr</td>
            </tr>

        </table>
        <br />
        {% if perms.costs.change_server %}
        <a href="{% url 'costs:application_form' %}?customer={{ application.customer.id }}&amp;name={{ application.name|urlencode }}">Endre {{ application.name }} hos {{application.customer }}</a>
        {% endif %}
        <br />
        {% if perms.costs.change_costdistribution %}
        <a href="{% url 'costs:cost_distribution' %}?application={{ application.id }}">Fordel kostander for {{ application.name }} hos {{application.customer }}</a>
        {% endif %}

    {% endfor %}

    {% if customer %}
        <br /><a href="{% url 'costs:application' %}?name={{ application_name|urlencode }}">Vis {{ application_name }} hos alle kunder</a>
    {% endif %}

{% endblock %}

costs/templates/costs/base.html
{% load static %}


<!DOCTYPE html>
<html lang="no">
<head>
    <meta charset="UTF-8">
    {% if not title %}
        <title>StorFollo IKT &oslash;konomimodell</title>
    {% else %}
        <title>StorFollo IKT &oslash;konomimodell - {{ title }}</title>
    {% endif %}

    <link rel="stylesheet" href="{% static 'admin/css/base.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'costs/costs.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'costs/menu.css' %}" type="text/css">
    <link rel="stylesheet" type="text/css"
          href="{% static 'costs/node_modules/datatables.net-dt/css/jquery.dataTables.min.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'costs/node_modules/datatables.net-fixedheader-dt/css/fixedHeader.dataTables.min.css' %}">
    <script src="{% static 'costs/node_modules/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'costs/node_modules/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'costs/node_modules/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
    <script src="{% static 'costs/node_modules/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'costs/node_modules/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'costs/node_modules/jszip/dist/jszip.min.js' %}"></script>
    <script src="{% static 'costs/menu.js' %}"></script>
    <script>$.extend(true, $.fn.dataTable.defaults, {
        "paging": false,
        "language": {"url": "{% static 'costs/Norwegian-Bokmal.json' %}"}
    });</script>
    {% block head %}
    {% endblock %}
</head>
<body>
<div class="menu">
    <img src="{% static 'costs/logo.png' %}" alt="StorFollo IKT logo" style="max-height: 50px"/>
    <div class="myNav">
        <ul class="top_menu">
            {% if perms.costs.view_application %}
                <li><a href="{% url 'costs:applications' %}">Applikasjoner</a></li>
            {% endif %}
            {% if perms.costs.view_server %}
                <li><a href="{% url 'costs:servers' %}">Servere</a></li>
            {% endif %}
            {% if perms.costs.view_customer %}
                <li><a href="{% url 'costs:customers' %}">Kunder</a></li>
            {% endif %}
            {% if perms.costs.view_sector %}
                <li><a href="{% url 'costs:sectors' %}">Sektorer</a></li>
            {% endif %}
            {% if perms.costs.view_application %}
                <li><a href="{% url 'costs:portfolio' %}">Porteføljeoversikt</a></li>
            {% endif %}
            {% if perms.costs.view_workstation %}
                <li><a href="{% url 'costs:workstations' %}">Arbeidsstasjoner</a></li>
            {% endif %}
            {% if perms.costs.view_application %}
                <li><a href="{% url 'costs:report' %}">Rapport</a></li>
            {% endif %}
            {% if perms.employee_info.view_resource %}
                <li><a href="{% url 'employee_info_browser:index' %}">Ansatte</a></li>
            {% endif %}
            {% if perms.costs.view_product %}
                <li><a href="{% url 'costs:products' %}">Tjenester</a> </li>
            {% endif %}
            {% if perms.costs.view_product %}
                <li><a href="{% url 'costs:licences' %}">Lisenser</a></li>
            {% endif %}
            {% if perms.costs.add_application %}
                <li><a href="{% url 'costs:application_form' %}">Ny applikasjon</a></li>
            {% endif %}
            {% if perms.costs.add_server %}
                <li><a href="{% url 'costs:server_form' %}">Ny server</a></li>
            {% endif %}
            {% if not user.is_authenticated %}
                <li><a href="{% url 'account_login' %}">Logg inn</a></li>
            {% else %}
                <li><a href="{% url 'account_logout' %}">Logg ut</a></li>
            {% endif %}
        </ul>
    </div>
</div>

<div id="content" class="flex">
    <h1>{{ title|capfirst }}</h1>
    {% block body %}
    {% endblock %}
</div>
</body>
</html>

costs/templates/costs/departments.html
{% extends 'costs/base.html' %}
{% load humanize %}
{% block body %}
    <table>
    <tr>
        <th>Kunde</th>
        <th>Nummer</th>
        <th>Navn</th>
    </tr>
    {% for department in departments %}
        <tr>
            <td>{{ department.customer }}</td>
            <td>{{ department.number}}
            <td>{{ department.name }}</td>
        </tr>
    {% endfor %}
    </table>

{% endblock %}

costs/templates/costs/licenses.html
{% extends 'costs/base.html' %}
{% load filter %}

{% block body %}
    <table>
        <tr>
            <th>Lisens</th>
            <th>Brukere totalt</th>
            {% for customer in customers %}
                <th>{{ customer.name }}</th>
            {% endfor %}
        </tr>
        {% for product in products.all %}
            <tr>
                <td><a href="{% url 'costs:licences' %}?product={{ product.name|urlencode }}">{{ product.name }}</a>
                </td>
                <td>{{ product.users.count }}</td>
                {% for customer in customers %}
                    <td>{{ product.users|filter_customer:customer }}</td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
{% endblock %}

costs/templates/costs/servers.html
{% extends 'costs/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'admin/css/changelists.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'costs/filter.css' %}" type="text/css">
    <script type="application/javascript" src="{% static 'costs/filter.js' %}"></script>
{% endblock %}
{% block body %}
    <div class="module filtered" id="changelist">
        <div id="filter">
            <h2>Filtrering</h2>
            <form method="get">
                <h3><label for="active_input">Aktiv siste dager</label></h3>
                {% if selected_customer %}
                    <input type="hidden" name="customer" value="{{ selected_customer }}">
                {% endif %}
                <input type="text" name="active" id="active_input" size="2" value="90"/>
                <input type="submit" value="Vis">
            </form>
        </div>
    </div>
    <div class="results">
        <table class="display">
            <thead>
            <tr>
                <th>Kunde</th>
                <th>Server</th>
                <th>Type</th>
                <th>Tjeneste</th>
                <th>Applikasjoner</th>
                <th>Sist aktiv</th>
            </tr>
            </thead>
            <tbody>
            {% for server in servers %}
                <tr>
                    <td><a href="?customer={{ server.customer }}">{{ server.customer }}</a></td>
                    <td>
                        <a href="{% url 'costs:server' customer=server.customer name=server.name %}">{{ server.name }}</a>
                    </td>
                    <td>{{ server.type|default:"" }}</td>
                    <td>{{ server.product }}</td>
                    <td>
                        <a href="{% url 'costs:applications' %}?customer={{ server.customer }}&server={{ server.name }}">{{ server.applications.count }}</a>
                    </td>
                    <td>{{ server.last_logon|default:"" }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <script>$(document).ready(function () {
        $('table.display').DataTable({
            "order": [[0, "asc"]],
            fixedHeader: {
                headerOffset: $('.myNav').outerHeight()
            }
        });
    });</script>

    {{ customers|json_script:'customer-data' }}
    {{ types|json_script:'type-data' }}
    {{ products|json_script:'product-data' }}
    <script type="application/javascript">
      const filter_group = new filterGroup('filter')
      filter_group.addFilterJson('customer', 'Etter kunde')
      filter_group.addFilterJson('type', 'Etter type')
      filter_group.addFilterJson('product', 'Etter tjeneste')
    </script>
{% endblock %}

costs/templates/costs/user.html
{% extends 'costs/base.html' %}

{% block body %}
    <table>
        <tr>
            <th>Kunde</th>
            <td>{{ user.customer }}</td>
        </tr>
        <tr>
            <th>Navn</th>
            <td>{{ user.name }}</td>
        </tr>
        {% if perms.ad_import.view_user %}
        <tr>
            <th>AD</th>
            <td>{{ user.ad_object }}</td>
        </tr>
        {% endif %}
        {% if perms.employee_info.view_resource and user.employee %}
            <tr>
                <th>Ansatt</th>
                <td><a href="{% url 'employee_info_browser:resource' %}?company={{ user.company }}&amp;employee={{ user.employee.resourceId }}">{{ user.employee.resourceId }}</a></td>
            </tr>
        {% endif %}
        {% if perms.costs.view_student and user.student %}
            <tr>
                <th>Elev</th>
                <td>{{ user.student }}</td>
            </tr>
        {% endif %}

    </table>

    {% if perms.costs.view_workstation and user.workstations.count %}
        <br/>
        <h2>Primærbruker av arbeidsstasjoner</h2>
        {% include 'costs/workstations.html' with workstations=user.workstations.all %}
    {% endif %}
    {% if perms.costs.view_workstation and user.workstations_user.count %}
        <br/>
        <h2>Siste bruker av arbeidsstasjoner</h2>
        {% include 'costs/workstations.html' with workstations=user.workstations_user.all %}
    {% endif %}
    <br/>

    {% if perms.costs.view_product and user.products.count %}
        <h2>Tjenester</h2>
        {% include 'costs/products_table.html' with products=user.products.all %}
    {% endif %}

    {% if show_pus and user.pus_id %}
        <a href="https://storfolloikt.pureservice.com/agent/app#/user/{{ user.pus_id }}/information">Vis bruker i
            PureService</a>
    {% endif %}

{% endblock %}